2023-06-06 14:58:10,761 ERROR: Exception on /edit_profile [GET] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 65, in edit_profile
    form.username.data = current_user.username.username
AttributeError: 'str' object has no attribute 'username'
2023-06-06 14:58:37,913 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:58:47,842 ERROR: Exception on /edit_profile [POST] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 57, in edit_profile
    current_user.username.username = form.username.data
AttributeError: 'str' object has no attribute 'username'
2023-06-06 14:59:09,612 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 15:01:30,118 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
