2023-06-07 17:24:29,193 ERROR: Exception on /user/mortimer/doctor/2/edit [POST] [in /home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'main.edit_doctor' did not return a valid response. The function either returned None or ended without a return statement.
2023-06-07 17:25:26,516 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:64]
2023-06-07 17:26:09,857 ERROR: Exception on /user/mortimer/doctor/15/edit [POST] [in /home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'main.edit_doctor' did not return a valid response. The function either returned None or ended without a return statement.
2023-06-08 11:02:44,650 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:64]
2023-06-08 11:03:03,504 ERROR: Exception on /user/mortimer/doctor/8/edit [POST] [in /home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'main.edit_doctor' did not return a valid response. The function either returned None or ended without a return statement.
2023-06-08 11:03:38,683 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:64]
2023-06-08 11:05:00,772 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:64]
2023-06-08 11:05:09,692 ERROR: Exception on /user/mortimer/doctor/8/edit [POST] [in /home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 305, in edit_doctor
    if form.validate_on_submit():
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/fields/core.py", line 242, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/fields/core.py", line 262, in _run_validation_chain
    validator(form, self)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/validators.py", line 138, in __call__
    length = field.data and len(field.data) or 0
TypeError: object of type 'int' has no len()
2023-06-08 11:06:16,613 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:64]
2023-06-08 11:06:21,499 ERROR: Exception on /user/mortimer/doctor/8/edit [POST] [in /home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 305, in edit_doctor
    if form.validate_on_submit():
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/fields/core.py", line 242, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/fields/core.py", line 262, in _run_validation_chain
    validator(form, self)
  File "/home/erica/portfolio/medication_tracker/venv/lib/python3.10/site-packages/wtforms/validators.py", line 138, in __call__
    length = field.data and len(field.data) or 0
TypeError: object of type 'int' has no len()
