2023-05-31 16:03:07,284 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-31 16:25:20,654 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-31 16:25:24,124 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-31 16:33:20,496 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-31 16:40:53,282 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-05-31 16:40:55,885 ERROR: Exception on /user/Mortimer/user_profile [GET] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 30, in user_profile
    form = EditProfileForm()
  File "/home/erica/.local/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: EditProfileForm.__init__() missing 2 required positional arguments: 'original_username' and 'original_email'
2023-06-06 13:16:24,951 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 13:20:06,281 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 13:20:29,037 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 13:26:52,498 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 13:26:55,442 ERROR: Exception on /user/Mortimer/user_profile [GET] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 30, in user_profile
    form = EditProfileForm(username)
  File "/home/erica/.local/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: EditProfileForm.__init__() missing 1 required positional argument: 'original_email'
2023-06-06 13:27:32,342 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 13:27:36,720 ERROR: Exception on /user/Mortimer/user_profile [GET] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 38, in user_profile
    return render_template('user_profile.html', title="User Profile",
  File "/home/erica/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/erica/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/erica/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/erica/portfolio/medication_tracker/app/templates/user_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/erica/portfolio/medication_tracker/app/templates/base.html", line 62, in top-level template code
    {% block content %}{% endblock %}
  File "/home/erica/portfolio/medication_tracker/app/templates/user_profile.html", line 37, in block 'content'
    {% for error in form.email %}
TypeError: 'EmailField' object is not iterable
2023-06-06 13:28:06,050 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:32:03,023 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:38:28,532 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:39:24,539 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:40:38,214 ERROR: Exception on /user/Munchbear/edit_profile [GET] [in /home/erica/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erica/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/erica/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/erica/portfolio/medication_tracker/app/main/routes.py", line 63, in edit_profile
    return render_template('edit_profile.html', title="Edit Profile",
  File "/home/erica/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/erica/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/erica/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/erica/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/erica/portfolio/medication_tracker/app/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/erica/portfolio/medication_tracker/app/templates/base.html", line 55, in top-level template code
    {% block header %} {% endblock %}
  File "/home/erica/portfolio/medication_tracker/app/templates/edit_profile.html", line 4, in block 'header'
    <h1 class="header">Edit Information - Dr. {{ doctor.full_name() }}</h1>
  File "/home/erica/.local/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'doctor' is undefined
2023-06-06 14:41:48,995 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:42:58,750 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:45:14,523 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:46:22,848 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:48:13,157 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:49:54,013 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:52:02,806 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:53:05,862 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
2023-06-06 14:57:57,244 INFO: Medication tracker startup [in /home/erica/portfolio/medication_tracker/app/__init__.py:61]
